channels:
  - r
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _r-mutex=1.0.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - bleach=4.1.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cmake=3.22.1
  - comm=0.1.2
  - curl=7.87.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gfortran_impl_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - glib=2.69.1
  - gmp=6.2.1
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=4.3.0
  - icu=58.2
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.4
  - lapack=3.6.0
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libuv=1.40.0
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - make=4.2.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - openssl=1.1.1t
  - packaging=22.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - pixman=0.40.0
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyrsistent=0.18.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pyzmq=23.2.0
  - r=4.2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.0
  - r-base64enc=0.1_3
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-blob=1.2.3
  - r-boot=1.3_28
  - r-brew=1.0_7
  - r-brio=1.1.3
  - r-broom=0.8.0
  - r-bslib=0.3.1
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-caret=6.0_92
  - r-cellranger=1.1.0
  - r-class=7.3_20
  - r-cli=3.3.0
  - r-clipr=0.8.0
  - r-cluster=2.1.3
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-commonmark=1.8.0
  - r-cpp11=0.4.2
  - r-crayon=1.5.1
  - r-credentials=1.3.2
  - r-crul=1.2.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.2
  - r-dbplyr=2.1.1
  - r-desc=1.4.1
  - r-devtools=2.4.3
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-dplyr=1.0.9
  - r-dtplyr=1.2.1
  - r-e1071=1.7_9
  - r-ellipsis=0.3.2
  - r-essentials=4.2
  - r-evaluate=0.15
  - r-fansi=1.0.3
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-fontawesome=0.2.2
  - r-forcats=0.5.1
  - r-foreach=1.5.2
  - r-foreign=0.8_82
  - r-formatr=1.12
  - r-fs=1.5.2
  - r-future=1.26.1
  - r-future.apply=1.9.0
  - r-gargle=1.2.0
  - r-generics=0.1.2
  - r-gert=1.6.0
  - r-ggplot2=3.3.6
  - r-gh=1.3.0
  - r-gistr=0.9.0
  - r-gitcreds=0.1.1
  - r-glmnet=4.1_4
  - r-globals=0.15.0
  - r-glue=1.6.2
  - r-gmp=0.6_5
  - r-googledrive=2.0.0
  - r-googlesheets4=1.0.0
  - r-gower=1.0.0
  - r-gtable=0.3.0
  - r-hardhat=0.2.0
  - r-haven=2.5.0
  - r-hexbin=1.28.2
  - r-highr=0.9
  - r-hms=1.1.1
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.5
  - r-httr=1.4.3
  - r-ids=1.0.1
  - r-ini=0.3.1
  - r-ipred=0.9_12
  - r-irdisplay=1.1
  - r-irkernel=1.3
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.0
  - r-kernsmooth=2.23_20
  - r-knitr=1.39
  - r-labeling=0.4.2
  - r-later=1.3.0
  - r-lattice=0.20_45
  - r-lava=1.6.10
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.1
  - r-listenv=0.8.0
  - r-lobstr=1.1.1
  - r-lubridate=1.8.0
  - r-magrittr=2.0.3
  - r-maps=3.4.0
  - r-mass=7.3_57
  - r-matrix=1.4_1
  - r-memoise=2.0.1
  - r-mgcv=1.8_40
  - r-mime=0.12
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-nlme=3.1_157
  - r-nnet=7.3_17
  - r-numderiv=2016.8_1.1
  - r-openssl=2.0.2
  - r-parallelly=1.31.1
  - r-pbdzmq=0.3_7
  - r-pillar=1.7.0
  - r-pkgbuild=1.3.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plyr=1.8.7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.5.3
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.10.0
  - r-promises=1.2.0.1
  - r-proxy=0.4_26
  - r-pryr=0.1.5
  - r-ps=1.7.0
  - r-purrr=0.3.4
  - r-quantmod=0.4.20
  - r-r6=2.5.1
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.8.3
  - r-rcpparmadillo=0.11.1.1.0
  - r-rcppeigen=0.3.3.9.2
  - r-readr=2.1.2
  - r-readxl=1.4.0
  - r-recipes=0.2.0
  - r-recommended=4.2
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.4.2
  - r-repr=1.1.4
  - r-reprex=2.0.1
  - r-reshape2=1.4.4
  - r-rlang=1.0.2
  - r-rmarkdown=2.14
  - r-roxygen2=7.2.0
  - r-rpart=4.1.16
  - r-rprojroot=2.0.3
  - r-rstudioapi=0.13
  - r-rversions=2.1.1
  - r-rvest=1.0.2
  - r-sass=0.4.1
  - r-scales=1.2.0
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.2
  - r-shape=1.4.6
  - r-shiny=1.7.1
  - r-sourcetools=0.1.7
  - r-spatial=7.3_15
  - r-squarem=2021.1
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.3_1
  - r-sys=3.4
  - r-testthat=3.1.4
  - r-tibble=3.1.7
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.2
  - r-tidyverse=1.3.1
  - r-timedate=3043.102
  - r-tinytex=0.39
  - r-triebeard=0.3.0
  - r-ttr=0.24.3
  - r-tzdb=0.3.0
  - r-urltools=1.7.3
  - r-usethis=2.1.6
  - r-utf8=1.2.2
  - r-uuid=1.1_0
  - r-vctrs=0.4.1
  - r-viridislite=0.4.0
  - r-vroom=1.5.7
  - r-waldo=0.4.0
  - r-whisker=0.4
  - r-withr=2.5.0
  - r-xfun=0.31
  - r-xml=3.99_0.9
  - r-xml2=1.3.3
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-xts=0.12.1
  - r-yaml=2.3.5
  - r-zip=2.2.0
  - r-zoo=1.8_10
  - readline=8.2
  - rhash=1.4.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sysroot_linux-64=2.12
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tktable=2.10
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - about-time==4.2.1
      - alive-progress==3.1.1
      - awslambdaric==2.0.4
      - bcrypt==4.0.1
      - boto3==1.26.109
      - botocore==1.29.114
      - charset-normalizer==3.1.0
      - contourpy==1.0.7
      - cryptography==40.0.2
      - cycler==0.11.0
      - dill==0.3.6
      - fonttools==4.39.3
      - globus-sdk==3.19.0
      - grapheme==0.6.0
      - importlib-resources==5.12.0
      - jmespath==1.0.1
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - numpy==1.24.2
      - pandas==1.5.3
      - paramiko==3.1.0
      - parsl==2023.4.17
      - patsy==0.5.3
      - pdf2image==1.16.3
      - pillow==9.5.0
      - pyjwt==2.6.0
      - pymupdf==1.22.0
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pypdf2==3.0.1
      - pytz==2023.3
      - reportlab==3.6.12
      - requests==2.28.2
      - s3transfer==0.6.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - setproctitle==1.3.2
      - sigprofilerassignment==0.0.29
      - sigprofilermatrixgenerator==1.2.14
      - sigprofilerplotting==1.3.12
      - simplejson==3.17.2
      - statsmodels==0.13.5
      - tblib==1.7.0
      - threadpoolctl==3.1.0
      - typeguard==2.13.3
      - types-paramiko==3.0.0.7
      - types-requests==2.28.11.17
      - types-six==1.16.21.8
      - types-urllib3==1.26.25.10
      - tzdata==2023.3
      - urllib3==1.26.15
      - zipp==3.15.0